#version: "3.8"
#services:
#  code-server:
#    build:
#      context: .
#      args:
#        GITHUB_REPO: mayank-vekariya/react-app
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./workspace:/project
#    restart: always
#version: '3.8'
#services:
#  dev-env:
#    build: .
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./project:/workspace
#    restart: always
