version: "3.8"
services:
  code-server:
    build:
      context: .
      args:
        GITHUB_REPO: mayank-vekariya/my-ide-cloud
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/workspace
    restart: unless-stopped
